### ISSUE TITLE
Where can I put my own js file

### ISSUE THREAD

**Issue by callalilychen** [HarborZeng/hexo-photoswipe#1]
Hello, I just begin with using hexo to build my own blog and I like to use the photoswipe feature for my pictures. So I just follow your readme. But I can not understand the step 3. Initialize in your own js file:
- Where should I put this js file with the content of step 3?
- Where should I include the js file

**Comment by HarborZeng** [comment]
any js file that your theme used.

for example:

https://github.com/zhwangart/hexo-theme-ocean/blob/3b99adbfc83e1fcdf9e5d8580ad2fc9d9325058d/source/js/ocean.js
